import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterWithChat from "@/component/Footer";
import Header from "@/component/Header";
// Style
import "../public/styles/style.css";
import "../public/styles/slick.css";
import "../public/styles/maggnific-popup.css";
import "../public/styles/fontawesome.min.css";
// import "@fortawesome/fontawesome-svg-core/styles.css";
// import { config } from "@fortawesome/fontawesome-svg-core";
import "../public/styles/default.css";
import "../public/styles/chat-tool.css";
import "../public/styles/bootstrap.min.css";
import "../public/styles/animate.css";
import Newsletter from "@/component/Newsletter";
import { ToastContainer } from "react-toastify";
import { DM_Sans, Exo } from 'next/font/google';

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',  // Optional, great for Tailwind or CSS variables
  display: 'swap',
});

const exo = Exo({
  subsets: ['latin'],
  variable: '--font-exo',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>

      <body className={`${dmSans.variable} ${exo.variable} ${dmSans.className}`}>
        <ToastContainer
          position="top-center"
          autoClose={4000}
          style={{ zIndex: "9999" }}
        />
        <Header />
        {children}
        <Newsletter />
        <FooterWithChat />
      </body>
    </html>
  );
}
