import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterWithChat from "@/component/Footer";
import Header from "@/component/Header";
// Style
import "../public/styles/style.css";
import "../public/styles/slick.css";
import "../public/styles/maggnific-popup.css";
import "../public/styles/fontawesome.min.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "../public/styles/default.css";
import "../public/styles/chat-tool.css";
import "../public/styles/bootstrap.min.css";
import "../public/styles/animate.css";
import Newsletter from "@/component/Newsletter";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastContainer
          position="top-center"
          autoClose={4000}
          style={{ zIndex: "9999" }}
        />
        <Header />
        {children}
        <Newsletter />
        <FooterWithChat />
      </body>
    </html>
  );
}
